name: combine

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v3
          with:
            python-version: '3.8.10'
            cache: 'pip'
      - uses: actions/upload-artifact@v3
          with:
            name: combination
            path: mw.pdf

      - name: Install dependencies
         run: pip install numpy scipy matplotlib pyyaml sorcery

      - name: Make plot
         run: python3 mw.py
